### ISSUE TITLE
Can't get docs to work

### ISSUE THREAD

**Issue by ndarilek** [jonsharratt/babel-graphql-js#7]
Hello, new to GraphQL here so I might be missing something. I wanted to see if I could get the graphiql docs subsystem to work, so I made the following change in the example:

```
{
  Character: {
    description: 'A character in the Star Wars Trilogy',
    resolveType: () => { return StarWarsSchema.Human; },
    id: {
      description: 'The id of the character.'
    },
    name: {
      description: 'The name of the character.'
    }
  },
  Droid: {
    description: 'A mechanical creature in the Star Wars universe.'
  },
  Query: {
    hero: {
      description: "Returns the hero of the specified episode"
    },
    human: {
      description: "Returns the specified Human"
    },
    droid: {
      description: "Returns the specified Droid"
    }
  }
}
}`;
```

But nothing happens when I click the docs button. Am I missing something?

Thanks for this project.

**Comment by jonsharratt** [comment]
Thanks for checking it out :D, looks like if you provide it as the second expression in the string literal it 'should' work.  If you pull down this repo and check out the `example` folder.  You can easily spin it up `node index.js` and play around with it at (via GraphiQL) at`http://localhost:3000`.

I quickly pasted in your example above and all seemed to work, here is the complete schema code I tried for what you are trying to achieve:

```
const StarWarsTypes = graphql`${`
enum Episode { NEWHOPE, EMPIRE, JEDI }

interface Character {
  id: String!
  name: String
  friends: [Character]
  appearsIn: [Episode]
}

type Human implements Character {
  id: String!
  name: String
  friends: [Character]
  appearsIn: [Episode]
  homePlanet: String
}

type Droid implements Character {
  id: String!
  name: String
  friends: [Character]
  appearsIn: [Episode]
  primaryFunction: String
}

type Query {
  hero(episode: Episode): Character
  human(id: String!): Human
  droid(id: String!): Droid
}

`}${
{
  Character: {
    description: 'A character in the Star Wars Trilogy',
    resolveType: () => { return StarWarsSchema.Human; },
    id: {
      description: 'The id of the character.'
    },
    name: {
      description: 'The name of the character.'
    }
  },
  Droid: {
    description: 'A mechanical creature in the Star Wars universe.'
  },
  Query: {
    hero: {
      description: "Returns the hero of the specified episode"
    },
    human: {
      description: "Returns the specified Human"
    },
    droid: {
      description: "Returns the specified Droid"
    }
  }
}
}`;
```

**Comment by ndarilek** [comment]
Interesting, that's exactly what I have, but instead I get this in my 
console when clicking Docs:

```
detailed error: TypeError: e.split is not a function
error source line:



...o),t=i+1)}return r}:function(e){return e.split(/\r\n?|\n/)},es=window.getSelecti...





graphiql.min.js (line 9, col 824)

```

Not sure what to do about that since all the code is minified. This is 
under the latest stable Firefox.

Thanks.

**Comment by ndarilek** [comment]
Huh, interesting, seems to work with Chrome. Is that true for you as 
well? Maybe this is a Graphiql issue.

**Comment by jonsharratt** [comment]
Yer not 100% sure, but using Firefox I get the same issue (I use Chrome).  Looks like it could well be a GraphiQL issue, noticed you have already raised this so let's see whether anyone else has any input to why this is potentially happening.  If I get chance later I will see if I can figure it out.

**Comment by jonsharratt** [comment]
As per the issue referenced, closing for now.
